spring.application.name=goandstudybackend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://goandstudyadmin:goandstudyadmin@goandstudycluster.4jz25t7.mongodb.net/?appName=goandstudycluster
spring.data.mongodb.database=goandstudydb

jwt.secret=GoAndStudySecretKey2026SuperSecureKeyForJWTSigning
jwt.expiration=86400000

cors.allowed.origins=http://localhost:8080,http://localhost:3001,http://localhost:3003,http://localhost:3000,http://localhost:3004,http://localhost:3005,http://localhost:3006,https://goandstudyfrontend.vercel.app,http://152.59.163.57:3003

realtime.server.url=http://localhost:3001
realtime.server.secret=GoAndStudyRealtimeSecret2026

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.goandstudybackend=DEBUG

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.write-empty-json-arrays=true
